spring:
  datasource:
    driver-class-name: org.sqlite.JDBC
   # url: jdbc:sqlite::resource:sqlite\w_robot
    url: jdbc:sqlite:D:/java/source/idea-project/robot/wechat_robot/src/main/resources/sqlite/w_robot

#mybatis
mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath:mapper/custom/*.xml
  type-aliases-package: tk.mybatis.springboot.model

#通用mapper
mapper:
  mappers:
    - tk.mybatis.mapper.common.Mapper
  notEmpty: true
#  identity: MYSQL

#分页插件
pagehelper:
  supportMethodsArguments: false
  reasonable: false
  helperDialect: sqlite
  params: count=countSql


logging:
  config: classpath:log/logback-spring.xml
  logPath: D:\java\data\log\wechat_robot\main
  logLevel: debug

#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    type: com.alibaba.druid.pool.DruidDataSource
#    url: jdbc:mysql://47.92.6.56:3306/wechat_robot?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
#    username: root
#    password: xm123456
#    druid:
#      initial-size: 5                               # 初始化时建立物理连接的个数
#      min-idle: 5                                   # 最小连接池数量
#      max-active: 10                                # 最大连接池数量
#      max-wait: 60000                               # 获取连接时最大等待时间，单位毫秒
#      test-while-idle: true                         # 建议配置为true，不影响性能，并且保证安全性。申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
#      test-on-borrow: true                          # 申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
#      test-on-return: false                         # 归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
#      time-between-eviction-runs-millis: 60000      # 配置检测可以关闭的空闲连接间隔时间
#      min-evictable-idle-time-millis: 300000        # 配置连接在池中的最小生存时间
#      max-evictable-idle-time-millis: 400000        # 配置连接在池中的最小生存时间
#      validation-query: SELECT 1 FROM DUAL          # 用来检测连接是否有效的sql，要求是一个查询语句
#      use-global-data-source-stat: true             # 合并多个DruidDataSource的监控数据
#
#      #开启监控
#      filter: stat,wall                             # 监控统计的stat,以及防sql注入的wall
#      connect-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500  # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
#      aop-patterns: com.xm.*.service.*              # Spring监控AOP切入点，如x.y.z.service.*,配置多个英文逗号分隔
#      stat-view-servlet:
#        enabled: true
#        reset-enable: true                          # 是否能够重置数据
#        login-username: manage
#        login-password: manage
#        url-pattern: /druid/*                       #访问路径为/druid时，跳转到StatViewServlet

#  rabbitmq:
#    host: 47.92.6.56
#    port: 5672
#    virtual-host: /wechat_robot
#    username: guest
#    password: guest
#    connection-timeout: 15000     #连接超时时间
#    type: simple
#    #    publisher-confirms: true
#    #    publisher-returns: true
#    listener:
#      simple:
#        acknowledge-mode: manual  #消费确认置为手动
#        prefetch: 1               #限流（海量数据，同时只能过来一条）
#        concurrency: 1            #消费端
#        max-concurrency: 10       #最大消费端数
#        default-requeue-rejected: false #  设置为false，消息重试失败后丢弃或发往死信队列
#        retry:
#          enabled: true           # 允许消息消费失败的重试
#          max-attempts: 3         # 消息最多消费次数3次
#          initial-interval: 10000 # 消息多次消费的间隔10秒
#
#  redis:
#    host: 127.0.0.1
#    #    password:
#    #    host: 47.92.6.56
#    #    password: kxy521yu
#    port: 6379
#    database: 0
#    timeout: 2000
#    jedis:
#      pool:
#        max-active: 8
#        max-wait: -1
#        max-idle: 8
#        min-idle: 0