spring:
  datasource:
    driver-class-name: org.sqlite.JDBC
#    url: jdbc:sqlite:sqlite.db   #默认jar包同级目录，此处仅供参考，推荐单独放一个固定目录
    url: jdbc:sqlite:D:\java\data\db\wechat_robot\sqlite.db
logging:
  config: classpath:log/logback-spring.xml
  logPath: D:\java\data\log\wxapi
  logLevel: debug