spring:
  datasource:
    driver-class-name: org.sqlite.JDBC
   # url: jdbc:sqlite::resource:sqlite\w_robot
    url: jdbc:sqlite:D:/java/source/idea-project/robot/wechat_robot/src/main/resources/sqlite/w_robot

logging:
  config: classpath:log/logback-spring.xml
  logPath: D:\java\data\log\wechat_robot\main
  logLevel: debug