server:
  port: 8202

spring:
  application:
    name: wechat-robot
  profiles:
    active: dev

#mybatis
mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath:mapper/custom/*.xml
  type-aliases-package: tk.mybatis.springboot.model

#通用mapper
mapper:
  mappers:
    - tk.mybatis.mapper.common.Mapper
  notEmpty: true
#  identity: MYSQL

#分页插件
pagehelper:
  supportMethodsArguments: false
  reasonable: false
  helperDialect: sqlite
  params: count=countSql